//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notesmarketplace1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellerNotesReportedIssue
    {
        public int Id { get; set; }
        public int NoteId { get; set; }
        public int ReportedByid { get; set; }
        public int againstDownloadId { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> Modifieddate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Download Download { get; set; }
        public virtual SellerNote SellerNote { get; set; }
        public virtual User User { get; set; }
    }
}
